export enum RESPONSE_CODES {
    SUCCESS = "00",
    FAILURE = "01",
    NOT_FOUND = "02",
    VALIDATION_ERROR = "03",
    UN_AUTHORIZED = "04",
    UN_AUTHENTICATION = "05",

    USER_BANNED = "1001"
}